### ISSUE TITLE
SDG keywords

### ISSUE THREAD

**Issue by LujainAlMansoori** [LujainAlMansoori/SDGLibrary#9]
When a resource is uploaded, if it is tagged by a specific SDG, the sdg needs to also be added to the tags in the following format. Otherwise, when i press on the filter to filter the materials by SDG, the resource does not come up, even if it is tagged by an SDG.  

const sdglist = [
    "SDG1 - No Poverty",
    "SDG2 - Zero Hunger",
    "SDG3 - Good Health and Well-being",
    "SDG4 - Quality Education",
    "SDG5 - Gender Equality",
    "SDG6 - Clean Water and Sanitation",
    "SDG7 - Affordable and Clean Energy",
    "SDG8 - Decent Work and Economic Growth",
    "SDG9 - Industry, Innovation, and Infrastructure",
    "SDG10 - Reduced Inequality",
    "SDG11 - Sustainable Cities and Communities",
    "SDG12 - Responsible Consumption and Production",
    "SDG13 - Climate Action",
    "SDG14 - Life Below Water",
    "SDG15 - Life on Land",
    "SDG16 - Peace and Justice Strong Institutions",
    "SDG17 - Partnerships to achieve the Goal",
  ];

<img width="1382" alt="Screenshot 2024-03-15 at 10 06 20 PM" src="https://github.com/LujainAlMansoori/SDGLibrary/assets/122256965/4e0f292c-481e-4ff7-b321-35badc5201c5">
<img width="1200" alt="Screenshot 2024-03-15 at 10 06 26 PM" src="https://github.com/LujainAlMansoori/SDGLibrary/assets/122256965/9910f11e-c480-46dd-b402-652a3eb584e1">

**Comment by LujainAlMansoori** [comment]
Hello, 

Did you resolve this issue? Could you show screenshots of how it works? It is still the old tagging process for me

**Comment by deepchandra02** [comment]
Hi, could you confirm that you running my branch and not the main? Because its not merged with main yet, hence the PR

**Comment by deepchandra02** [comment]
<img width="799" alt="Screenshot 2024-03-21 at 9 54 28 AM" src="https://github.com/LujainAlMansoori/SDGLibrary/assets/64948485/9a75571f-c9a9-4b5d-bd3e-209ecf615291">
